version: '3.5'

services:
  angular-docker-sample:
    container_name: angular-docker-sample
    image: angular-docker-sample
    build:
      context: .
      dockerfile: ./Dockerfile # The path to Dockerfile. In this project it is in the same folder as docker-compose
      target: angular-docker-sample
    ports:
      - "5001:80" # Map 5001 port to 80 port. Nginx is configured to listen to 80 port in nginx.conf
